export const SESSION_LOAD_MORE_INIT = 'SESSION_LOAD_MORE_INIT';
export const SESSION_LOAD_MORE_BEGIN = 'SESSION_LOAD_MORE_BEGIN';
export const SESSION_LOAD_MORE_SUCCESS = 'SESSION_LOAD_MORE_SUCCESS';
export const SESSION_LOAD_MORE_FAILURE = 'SESSION_LOAD_MORE_FAILURE';
export const SESSION_LOAD_MORE_DISMISS_ERROR = 'SESSION_LOAD_MORE_DISMISS_ERROR';
