import React from 'react';
import { SocialIcon } from 'react-social-icons';
import { FormattedMessage } from 'react-intl';
import {
  Home as HomeIcon,
  About as AboutIcon,
  Login as LoginIcon,
  Logout as LogoutIcon,
  Cause as CauseIcon,
  Person as PersonIcon,
  Donation as DonationIcon,
  System as SystemIcon,
  Datas as DatasIcon,
  Dashboard as DashboardIcon,
} from '../icons';

export const globalMenu = [
  {
    icon: <HomeIcon />,
    label: <FormattedMessage id="app.features.home.app.menu.home" defaultMessage="Home" />,
    url: '/',
    role: 'HOME',
    public: true,
  },
  {
    icon: <LoginIcon />,
    label: <FormattedMessage id="app.features.home.app.menu.signin" defaultMessage="Sign in" />,
    url: '/auth/signin',
    role: 'SIGNIN',
    public: true,
  },
  {
    icon: <LogoutIcon />,
    label: <FormattedMessage id="app.features.home.app.menu.signout" defaultMessage="Sign out" />,
    url: '/auth/signout',
    role: 'SIGNOUT',
    public: false,
  },
  {
    icon: <SocialIcon url="https://facebook.com/KalaweitFrance/" />,
    label: 'Facebook',
    url: null,
    role: 'SOCIAL',
    position: 1,
    public: true,
  },
  {
    icon: <DashboardIcon />,
    label: (
      <FormattedMessage id="app.features.home.app.menu.dashboard" defaultMessage="Dashboard" />
    ),
    url: '/dashboard',
    role: 'NAV',
    position: 1,
    public: false,
  },
  {
    icon: <PersonIcon />,
    label: 'Membres',
    url: '/client',
    role: 'NAV',
    position: 2,
    public: false,
  },
  {
    icon: <CauseIcon />,
    label: 'Causes',
    url: '/cause',
    role: 'NAV',
    position: 3,
    public: false,
  },
  {
    icon: <DonationIcon />,
    label: 'Dons',
    url: '/donation',
    role: 'NAV',
    position: 4,
    public: false,
  },
  {
    icon: <DatasIcon />,
    label: 'Administratif',
    url: null,
    role: 'MENU',
    position: 5,
    public: false,
    options: [
      {
        icon: null,
        label: 'Types de paiement',
        url: '/payment-type',
        role: 'NAV',
        position: 1,
      },
    ],
  },
  {
    icon: <DatasIcon />,
    label: 'Répertoires',
    url: null,
    role: 'MENU',
    position: 6,
    public: false,
    options: [
      {
        icon: null,
        label: 'Sites',
        url: '/site',
        role: 'NAV',
        position: 1,
      },
      {
        icon: null,
        label: 'Types de site',
        url: '/site-type',
        role: 'NAV',
        position: 2,
      },
      {
        icon: null,
        label: 'Types de cause',
        url: '/cause-type',
        role: 'NAV',
        position: 3,
      },
      {
        icon: null,
        label: 'Grandes cause',
        url: '/cause-main-type',
        role: 'NAV',
        position: 4,
      },
      {
        icon: null,
        label: 'Catégories de personne',
        url: '/client-category',
        role: 'NAV',
        position: 5,
      },
      {
        icon: null,
        label: 'Types de personne',
        url: '/client-type',
        role: 'NAV',
        position: 6,
      },
      {
        icon: null,
        label: 'Variables',
        url: '/data',
        role: 'NAV',
        position: 99,
      },
    ],
  },
  {
    icon: <SystemIcon />,
    label: 'Paramétrage',
    url: null,
    role: 'MENU',
    position: 7,
    public: false,
    options: [
      {
        icon: null,
        label: 'Emails',
        url: '/email',
        role: 'NAV',
        position: 1,
      },
    ],
  },
  {
    icon: <AboutIcon />,
    label: 'Qui sommes nous ?',
    url: '/about',
    role: 'ABOUT',
    public: true,
  },
];
