import React from 'react';
import { SocialIcon } from 'react-social-icons';
import { FormattedMessage } from 'react-intl';
import {
  Administrative as AdministrativeIcon,
  Home as HomeIcon,
  About as AboutIcon,
  Login as LoginIcon,
  Logout as LogoutIcon,
  Cause as CauseIcon,
  Person as PersonIcon,
  Donation as DonationIcon,
  System as SystemIcon,
  Datas as DatasIcon,
  Dashboard as DashboardIcon,
  Certificate as CertificateIcon,
  Receipt as ReceiptIcon,
} from '../icons';

export const globalMenu = [
  {
    icon: <HomeIcon />,
    label: <FormattedMessage id="app.features.home.app.menu.home" defaultMessage="Home" />,
    url: '/',
    role: 'HOME',
    public: true,
  },
  {
    icon: <LoginIcon />,
    label: <FormattedMessage id="app.features.home.app.menu.signin" defaultMessage="Sign in" />,
    url: '/auth/signin',
    role: 'SIGNIN',
    public: true,
  },
  {
    icon: <LogoutIcon />,
    label: <FormattedMessage id="app.features.home.app.menu.signout" defaultMessage="Sign out" />,
    url: '/auth/signout',
    role: 'SIGNOUT',
    public: false,
  },
  {
    icon: <SocialIcon url="https://facebook.com/KalaweitFrance/" />,
    label: 'Facebook',
    url: null,
    role: 'SOCIAL',
    position: 1,
    public: true,
  },
  {
    icon: <DashboardIcon />,
    label: (
      <FormattedMessage id="app.features.home.app.menu.dashboard" defaultMessage="Dashboard" />
    ),
    url: '/dashboard',
    role: 'NAV',
    position: 1,
    public: false,
  },
  {
    icon: <PersonIcon />,
    label: 'Membres',
    url: '/client',
    role: 'NAV',
    position: 2,
    public: false,
  },
  {
    icon: <CauseIcon />,
    label: 'Causes',
    url: '/cause',
    role: 'NAV',
    position: 3,
    public: false,
  },
  {
    icon: <DonationIcon />,
    label: 'Dons',
    url: '/donation',
    role: 'NAV',
    position: 4,
    public: false,
  },
  {
    icon: <ReceiptIcon />,
    label: 'Reçus',
    url: '/receipt',
    role: 'NAV',
    position: 5,
    public: false,
  },
  {
    icon: <CertificateIcon />,
    label: 'Certificats',
    url: '/certificate',
    role: 'NAV',
    position: 6,
    public: false,
  },
  {
    icon: <AdministrativeIcon />,
    label: 'Administratif',
    url: null,
    role: 'MENU',
    position: 10,
    public: false,
    options: [
      {
        icon: null,
        label: 'Types de paiement',
        url: '/payment-type',
        role: 'NAV',
        position: 1,
      },
      {
        icon: null,
        label: 'Missions',
        url: '/cause-type',
        role: 'NAV',
        position: 3,
      },
    ],
  },
  {
    icon: <SystemIcon />,
    label: 'Paramétrage',
    url: null,
    role: 'MENU',
    position: 20,
    public: false,
    options: [
      {
        icon: null,
        label: 'Localisations',
        url: '/site',
        role: 'NAV',
        position: 1,
      },
      {
        icon: null,
        label: 'Types de localisation',
        url: '/site-type',
        role: 'NAV',
        position: 2,
      },
      {
        icon: null,
        label: 'Programmes',
        url: '/cause-main-type',
        role: 'NAV',
        position: 4,
      },
      {
        icon: null,
        label: 'Catégories de personne',
        url: '/client-category',
        role: 'NAV',
        position: 5,
      },
      {
        icon: null,
        label: 'Types de personne',
        url: '/client-type',
        role: 'NAV',
        position: 6,
      },
      {
        icon: null,
        label: 'Espèces',
        url: '/species',
        role: 'NAV',
        position: 8,
      },
      {
        icon: null,
        label: 'Sous-espèces',
        url: '/subspecies',
        role: 'NAV',
        position: 9,
      },
      {
        icon: null,
        label: 'Emails',
        url: '/email',
        role: 'NAV',
        position: 20,
      },
      {
        icon: null,
        label: 'Variables',
        url: '/data',
        role: 'NAV',
        position: 99,
      },
    ],
  },
  {
    icon: <AboutIcon />,
    label: 'Qui sommes nous ?',
    url: '/about',
    role: 'ABOUT',
    public: true,
  },
];
