export const RECEIPT_LOAD_MORE_INIT = 'RECEIPT_LOAD_MORE_INIT';
export const RECEIPT_LOAD_MORE_BEGIN = 'RECEIPT_LOAD_MORE_BEGIN';
export const RECEIPT_LOAD_MORE_SUCCESS = 'RECEIPT_LOAD_MORE_SUCCESS';
export const RECEIPT_LOAD_MORE_FAILURE = 'RECEIPT_LOAD_MORE_FAILURE';
export const RECEIPT_LOAD_MORE_DISMISS_ERROR = 'RECEIPT_LOAD_MORE_DISMISS_ERROR';
