export const PAYMENT_TYPE_LOAD_MORE_INIT = 'PAYMENT_TYPE_LOAD_MORE_INIT';
export const PAYMENT_TYPE_LOAD_MORE_BEGIN = 'PAYMENT_TYPE_LOAD_MORE_BEGIN';
export const PAYMENT_TYPE_LOAD_MORE_SUCCESS = 'PAYMENT_TYPE_LOAD_MORE_SUCCESS';
export const PAYMENT_TYPE_LOAD_MORE_FAILURE = 'PAYMENT_TYPE_LOAD_MORE_FAILURE';
export const PAYMENT_TYPE_LOAD_MORE_DISMISS_ERROR = 'PAYMENT_TYPE_LOAD_MORE_DISMISS_ERROR';
export const PAYMENT_TYPE_CLEAR_ITEMS = 'PAYMENT_TYPE_CLEAR_ITEMS';
